# Site settings
title: "Luke Savage"
email: luke.savage92@gmail.com
description: "A simple software engineering blog"
baseurl: ""
url: "http://lukesavage.me/"
title_description: "Software engineer with a focus in full-stack web development currently studying at Hack Reactor's Remote Beta program."
title_image: "http://i.imgur.com/yd8w2gY.png"
google_analytics: "UA-65251027-1"
disqus_account: lukesavage
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: lsavage92
github_username:  lsavage92
linkedin_link: https://www.linkedin.com/in/savageluke
google_plus_link:
stackoverflow_link: http://stackoverflow.com/users/1378664/lsavage

# Footer
footer_left: "&copy; Copyright 2015 Luke Savage"
footer_right: "Fork on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
